[general]
import = [
    "~/.config/alacritty/theme.toml"
]

[font]
size = 14.625

[font.normal]
family = "FiraCode Nerd Font"

[window.dimensions]
columns = 80
lines = 24

[window.padding]
x = 4
y = 4

[mouse]
hide_when_typing = true
