[general]
import = [
    "~/.config/alacritty/theme.toml"
]

[font]
size = 16.25

[font.normal]
family = "Fira Code"
style = "Regular"

[window.dimensions]
columns = 80
lines = 24

[window.padding]
x = 4
y = 4

[mouse]
hide_when_typing = true
