source $HOME/.config/nvim/general/settings.vim
source $HOME/.config/nvim/keys/mappings.vim
source $HOME/.config/nvim/vim-plug/plugins.vim
source $HOME/.config/nvim/plug-config/lsp-config.vim
source $HOME/.config/nvim/general/theme.vim
luafile $HOME/.config/nvim/lua/plugins/compe-config.lua
luafile $HOME/.config/nvim/lua/lsp/go-ls.lua
luafile $HOME/.config/nvim/lua/lsp/rust-ls.lua
luafile $HOME/.config/nvim/lua/lsp/c-ls.lua
luafile $HOME/.config/nvim/lua/lsp/ts-ls.lua
